repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.7

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8

  - repo: https://github.com/prettier/prettier
    rev: 1.16.1
    hooks:
      - id: prettier

  - repo: local
    hooks:
      - id: eslint
        name: eslint
        files: 'frontend/.*\.js$'
        entry: frontend/eslint.sh
        language: node
        types: [text]
