# docker-compose.yml
# Copyright (C) 2018 shady <shady@MrRobot.local>
#
version: "3"
services:
  mysql:
    image: itechub/jane-mysql:latest
    build: ./deployment/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ${DOCKER_DIR}/volumes/data:/var/lib/mysql # mysql data source
      - ${DOCKER_DIR}/volumes/log:/disk/log  # mysql log
    networks:
      - jane

  django:
    image: itechub/jane-django:latest
    container_name: django
    build:
      context: ./
      dockerfile: ./deployment/django/Dockerfile
    environment:
      HOST: mysql
      PORT: 3306
      DJANGO_MANAGEPY_MIGRATE: "on"
      DJANGO_MANAGEPY_COLLECTSTATIC: "on"
      USERNAME: root
      NAME: jane
      DEBUG: 1
      PASSWORD: ${DB_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      SENTRY: ${SENTRY}
    # mount django static file, serverd by nginx
    volumes:
      - ${DOCKER_DIR}/volumes/statics:/env/app/collectstatic/statics 
    networks:
      - jane

  react:
    image: itechub/jane-react:latest
    build: 
      context: ./
      dockerfile: ./deployment/react/Dockerfile
    environment:
        REACT_APP_BACKEND_API: http://localhost:8000
    ports:
      - "1984:80"
    volumes:
        - ${DOCKER_DIR}/volumes/statics:/usr/share/nginx/statics
    networks:
      - jane


networks:
  jane:
