# docker-compose.yml
# Copyright (C) 2018 shady <shady@MrRobot.local>
#
version: "3"
services:
  mysql:
    image: itechub/jane-mysql:latest
    build: ./deployment/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${JANE_DB_PASSWORD}
      MYSQL_DATABASE: ${JANE_DB_NAME}
    volumes:
      - ${DOCKER_DIR}/volumes/data:/var/lib/mysql # mysql data source
      - ${DOCKER_DIR}/volumes/log:/disk/log # mysql log
    networks:
      - jane

  django:
    image: itechub/jane-django:latest
    build:
      context: ./
      dockerfile: ./deployment/django/Dockerfile
    environment:
      DJANGO_MANAGEPY_MIGRATE: "on"
      DJANGO_MANAGEPY_COLLECTSTATIC: "on"
      JANE_DEBUG: ${JANE_DEBUG}
      JANE_SECRET_KEY: ${JANE_SECRET_KEY}
      JANE_DB_HOST: mysql
      JANE_DB_PORT: 3306
      JANE_DB_USERNAME: ${JANE_DB_USERNAME}
      JANE_DB_PASSWORD: ${JANE_DB_PASSWORD}
      JANE_DB_NAME: ${JANE_DB_NAME}
      JANE_SENTRY: ${JANE_SENTRY}
      JANE_ADMIN_NAME: ${JANE_ADMIN_NAME}
      JANE_ADMIN_EMAIL: ${JANE_ADMIN_EMAIL}
      JANE_ADMIN_PASS: ${JANE_ADMIN_PASS}
    # mount django static file, served by nginx
    volumes:
      - ${DOCKER_DIR}/volumes/statics:/env/app/collectstatic/statics
    networks:
      - jane

  nginx:
    image: itechub/jane-nginx:latest
    build:
      context: ./
      dockerfile: deployment/nginx/Dockerfile
      args:
        REACT_APP_JANE_API: ${REACT_APP_JANE_API}
    ports:
      - "1984:80"
    volumes:
      - ${DOCKER_DIR}/volumes/statics:/usr/share/nginx/statics
    networks:
      - jane

networks:
  jane:
