# docker-compose.yml
# Copyright (C) 2018 shady <shady@MrRobot.local>
#
version: "3"
services:
  nginx:
    image: itechub/jane-nginx:v1.0 
    build: ./deployment/nginx
    ports:
      - "10001:80"
    networks:
      - jane
        
  django:
    image: itechub/jane-django:v1.0
    build: 
        context: ./ 
        dockerfile: ./deployment/django/Dockerfile
    ports:
      - "10002:8080"
    environment:
        - HOST=mysql
        - PORT=3306
        - DJANGO_MANAGEPY_MIGRATE=on
        - DJANGO_MANAGEPY_COLLECTSTATIC=on
        - USERNAME=root
        - NAME=jane
        - DEBUG=True
        - PASSWORD=${DB_PASSWORD}
        - SECRET_KEY=${SECRET_KEY}
        - SENTRY=${SENTRY}
    networks:
      - jane

  mysql:
    image: itechub/jane-mysql:v1.0
    build: ./deployment/mysql
    environment:
      MYSQL_ROOT_PASSWORD: janepassword
    volumes:
      - ${DOCKER_DIR}/volumes/data:/var/lib/mysql # mysql data source
      - ${DOCKER_DIR}/volumes/log:/disk/log  # mysql log
    networks:
      - jane

networks:
  jane:
